// 导出员工ID
export const SERVICES_UPDATE_ID = 'SERVICES_UPDATE_ID'
// 获取、设置未读信息
export const SET_UNREAD_MESSAGE_UNM = 'SET_UNREAD_MESSAGE_UNM'

// 获取初始化数据
export const SET_INITIAL_DATA = 'SET_INITIAL_DATA'

// 获取考勤徽章
export const FETCH_ATTENDANCE_BADGE = 'FETCH_ATTENDANCE_BADGE'
